# Generated by Django 5.1.5 on 2025-02-26 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('total_land', models.FloatField()),
                ('land_unit', models.CharField(choices=[('acre', 'Acre'), ('hectare', 'Hectare')], max_length=20)),
                ('location_of_farm', models.CharField(max_length=700)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('addhar_image', models.ImageField(null=True, upload_to='farmer_addhar')),
                ('become_farmer_vendor', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmEquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='farm_equipment/')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_images', to='user.becomefarmer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=80, null=True)),
                ('city', models.CharField(max_length=80, null=True)),
                ('profile_image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
